In [11]:
import numpy as siva
a=siva.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("original siva:\n",a)
print("\nEvery other rows:arr[0:3:2]:\n",a[0:3:2])
temp=a[:2,:3]
print("\nArray with first 2 rows and 3 columns[:2,:3]:\n",temp)
temp=a[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1),""(3,0):\n",temp)
cond=a>2
temp=a[cond]
print("\nElements greater than 2:\n",temp)
a=siva.array([1,2,3,4,5,6,7])
print("\nOriginal array:",a)
print("\nReturns every other elements in the array:a[::2]:",a[::2])

original siva:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

Every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]

Array with first 2 rows and 3 columns[:2,:3]:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]

Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]

Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]

Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:a[::2]: [1 3 5 7]


In [15]:
arr1=siva.array([1,2,3])
arr2=siva.array([4,5,6])
a=siva.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\njoined array:\n",a)
a=siva.hstack((arr1,arr2))
print("\nHorizondal joining:\n",a)
a=siva.vstack((arr1,arr2))
print("\nVertical joining:\n",a)
a=siva.dstack((arr1,arr2))
print("\nDepth joining:\n",a)
a=siva.array([1,2,3,4,5,6])
newarr=siva.array_split(a,3)
print("\nOriginal Array:\n",a)
print("\nsplitted array:\n",newarr)



Original arrays:
 [1 2 3] [4 5 6]

joined array:
 [1 2 3 4 5 6]

Horizondal joining:
 [1 2 3 4 5 6]

Vertical joining:
 [[1 2 3]
 [4 5 6]]

Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]

Original Array:
 [1 2 3 4 5 6]

splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
print("\nSplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Splitted array in another form:

[1 2]
[3 4]
[5 6]
