In [16]:
import numpy as siva
a=siva.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=siva.zeros((3,4))
print("The Element in array is",b)
c=siva.full((3,3),7)
print(c)
d=siva.random.random((2,2))
print(d)
e=siva.arange(0,10,2)
print(e)
f=siva.array([[1,2,3,4],[5,6,7,8],[2,4,6,7]])
g=f.reshape(4,3)
print(f)
print(g)
h=f.astype('f')
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The Element in array is [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.27619398 0.13012787]
 [0.43503727 0.54310742]]
[0 2 4 6 8]
[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 7]]
[[1 2 3]
 [4 5 6]
 [7 8 2]
 [4 6 7]]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 4. 6. 7.]]


In [17]:
a=siva.empty((8,4))
for i in range (8):
    a[i]=i
print (a)
print (a[[1,2,3,4]])
print (a[[-2,-3,-4]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
[[6. 6. 6. 6.]
 [5. 5. 5. 5.]
 [4. 4. 4. 4.]]


In [6]:
import numpy as surya
a=surya.array([[-1,2,0,4],[4,0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print(a)

[[-1.   2.   0.   4. ]
 [ 4.   0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
